version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=todo
      - DB_USER=airdev
      - DB_PASS=2000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=airdev
      - POSTGRES_PASSWORD=2000
    volumes: 
      - db:/var/lib/postgresql/data
volumes: 
  db:
    driver: local