version: '3.7'

services:
  web:
    volumes:
      - static:/code/static
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=todo
      - DB_USER=airdev
      - DB_PASS=2000
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=airdev
      - POSTGRES_PASSWORD=2000
    volumes: 
      - db:/var/lib/postgresql/data
  nginx:
    build: nginx
    restart: always
    volumes:
      - static:/code/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes: 
  static:
  db:
    driver: local