# Generated by Django 4.0.4 on 2022-04-30 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Task Tittle')),
                ('description', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Task Description')),
                ('status', models.CharField(choices=[('0', 'todo'), ('1', 'In Progress'), ('2', 'Done')], default='0', max_length=1)),
                ('due_Date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['due_Date'],
            },
        ),
    ]
